language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src

install:
    - pip install -U platformio
    - platformio update

    #
    # Libraries from PlatformIO Library Registry:
    #
    # https://platformio.org/lib/show/4ee/
    # https://platformio.org/lib/show/c23/
    # - platformio lib -g install 4ee c23

addons:
    apt:
        packages:
            - doxygen

script:
    # check for trailing white spaces (comparing with first commit in git log)
    - git diff --check `git rev-list HEAD | tail -n 1`..$TRAVIS_BRANCH
    - cp src/config.h_template src/config.h
    - platformio run -e mppt-2420-lc-v0.10 -e mppt-1210-hus-v0.2 -e mppt-1210-hus-v0.4 -e pwm-2420-lus-v0.2
    - platformio test -e unit-test-native
    - doxygen Doxyfile

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: html
    github_token: $GH_REPO_TOKEN
    on:
        repo: LibreSolar/charge-controller-firmware
        branch: master
