language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src

install:
    - pip install -U platformio
    - platformio update

    #
    # Libraries from PlatformIO Library Registry:
    #
    # https://platformio.org/lib/show/4ee/
    # https://platformio.org/lib/show/c23/
    # - platformio lib -g install 4ee c23 

script:
        - cp src/config.cpp.LeadAcid.template src/config.cpp
        - platformio ci --lib="lib/Adafruit_GFX" --project-conf=platformio.ini 
